### PR TITLE
GetCommentsCount always returns 0 so comments never work

### PR DESCRIPTION
**Pull request by DavidTanner**
It would appear this field doesn't get populated correctly so don't use it for now.

### CODE REVIEW

**Comment by DavidTanner** [comment]
@mmitche Either there is a bug in the github api, or github.

**Comment by mmitche** [comment]
In the newer versions I think it works properly (using it now)

**Comment by DavidTanner** [comment]
@mmitche are you just using webhooks though?  If that is the case it would never check here for comments.

**Comment by mmitche** [comment]
@DavidTanner In this case yeah.  If we hit a restart, it will do an initial check for comments

**Pull request merged**
