### PR TITLE
Make using git's merge commits as an option, rather than always.

### PR DESCRIPTION
**Pull request by benpatterson**
Hi! - 

We had a need for this on our team so I wanted to contribute if this would be useful to others.

It's similar to #59 but in this case it's configurable per job.

### CODE REVIEW

**Comment by DavidTanner** [comment]
Why not just use the actual commit variable in the gut plugin?  That is what you are doing here anyways, then we don't have to add another configuration.

**Comment by benpatterson** [comment]
@DavidTanner Sorry...what do you mean? Where would I specify that? Any insight would be awesome.

**Comment by DavidTanner** [comment]
Instead of using ${sha1} use ${ghprbActualCommit}

On Fri, Jan 16, 2015 at 7:20 AM, Ben Patterson <notifications@github.com>
wrote:

> @DavidTanner <https://github.com/DavidTanner> Sorry...what do you mean?
> Where would I specify that? Any insight would be awesome.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/jenkinsci/ghprb-plugin/pull/71#issuecomment-70259492>.
>



-- 
David Tanner

3 Nephi 5:13 <http://lds.org/scriptures/bofm/3-ne/5.13?lang=eng#12> Behold,
I am a disciple of Jesus Christ, the Son of God. I have been called of him
to declare his word among his people, that they might have everlasting life.

**Comment by benpatterson** [comment]
Hey @DavidTanner I gave this a try. Specifically, I replaced ${sha1} with ${ghprbActualCommit} in the Branch Specifier field on the git / scm configuration for my job. I then worked on an active PR, made a change, and pushed. The webhook was enabled and the job started. However, it still automatically merged for me, using origin/pr/<id>/merge.

I can see that it merged it because I deliberately checked in a file to master that is not in my branch, but I see that it was used in the job, and it's in the workspace after the job completes.

Perhaps I changed configuration in the wrong place? Any advice would be great!

Output example here... The actual commit starts with 527... And the revision starting with 744 is the merge commit:

```
GitHub pull request #9 of commit 527e91cd450e5a96d92d9b1cd6226dc5e1c19b46 automatically merged.

Revision: 7447364d3a7122b6dfa749741b52c169c576e877
* origin/pr/9/merge
```

**Comment by DavidTanner** [comment]
I found the real issue!!  Took commenting out every parameter set by GhprbTrigger.  After the parameters are all set, and the trigger is creating a new build it creates a RevisionParameterAction, locking git to using the sha1 value.  Git then ignores anything you put in the plugin for branch specifier.  
https://github.com/jenkinsci/ghprb-plugin/blob/f2cb99b77bea3ec46a0f75f71ebabf841058a7bb/src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java#L182

I am working on adding multiple credentials for the plugin.  Once I get that merged I will release a new version that will include this fix.

**Comment by DavidTanner** [comment]
Behavior since 02ad97d165f18cb80301f464625c4f4f7d78b7d0 
I don't like adding new config settings, and in this case it would make more sense to me to allow a per job configuration base don the variable you use.  sha1 represents the merged commit version created by github, and (currently) ghprbActualCommit represents the actual commit that started the build.

**Comment by benpatterson** [comment]
@DavidTanner Thanks for looking into this! Your comments and the line you point out make sense. I'm happy to put in a cycle to help get this fixed. Let me know if I can jump in for you. Otherwise I'll look forward to seeing this fixed by the changes you're working on.

**Comment by benpatterson** [comment]
Hi @DavidTanner I see the new release pushed out this weekend, and...
* Cool! If I use ${ghprbActualCommit} as the branch specifier, it will NOT automatically merge the code, and run the build on the PR's head. 
* The messaging is a bit confusing though, as the gitHub status will report "Merged Build started/finished" when it's running/has completed.
* Similarly, the revision history (appearing on the front page of my job, at least) has a message like this: 
```
GitHub pull request #9 of commit f02c8dac5381bff86d6703936926973133976aa1 automatically merged.
```
That's the right commit, but it wasn't merged.

Any suggestions? Thanks again for all the help!

**Comment by DavidTanner** [comment]
So the confusion is in the verbage. Github will always try and merge the pull request. If it can then that commit sha becomes available for use.  Whether you use it or not is up to you. 

what do you think the wording should be?  More or less verbose?

**Comment by benpatterson** [comment]
Hey @DavidTanner -- well the original issue has been addressed (i.e. having a way for us to not-merge automatically), and that's awesome. What I mentioned in the last comment though is, yes, the verbiage. If I have a commit that cannot be automatically merged, then the wording I see on the github status, for example is just "build started". However, with the current fix+configuration, I'll see "merged build started" which to me implies that my commit has been automatically merged, and that *merged commit* is what's being tested. But, that's not the case when using the ghprbActualCommit.

Thanks for any insight on that....

**Comment by DavidTanner** [comment]
I will make a pull request for the wording today so we can get some feedback.

**Comment by DavidTanner** [comment]
Fixed in the latest release.

**Pull request closed without merging**
