### PR TITLE
Optionally check merge commits

### PR DESCRIPTION
**Pull request by chornlgscout**
Option to trigger a rebuild based on the merge commit (which is to say, commits to the branch to be merged or the branch to be merged to).

### CODE REVIEW

**Comment by DavidTanner** [comment]
I don't understand what this is trying to do, shouldn't we build if the base or target have changed and hence the merge sha has changed?

**Comment by chornlgscout** [comment]
If new commits were to occur on jenkinsci:master now, neither the base nor head for this pull request would not be updated, no.

**Comment by chornlgscout** [comment]
@DavidTanner do you need further clarification?

**Comment by DavidTanner** [comment]
I don't think we actually need to make this an option, the job should run if anything affecting the pr has changed

**Comment by chornlgscout** [comment]
Do you mean it should be default behavior? Or that it should never rebuild a PR when only the target branch has changed?

**Comment by DavidTanner** [comment]
I would think that by default it should rebuild if the base or target have changed.

**Comment by chornlgscout** [comment]
I would think you would also want to check the head. And I believe that the easiest way to check the target and the head is via the merge commit.

**Comment by chornlgscout** [comment]
So should I remove the checkbox and make the merge check the default?

**Comment by benpatterson** [comment]
Hi - I'm lending @DavidTanner a hand with code reviews and such. 

With the change as-is, I'm wondering if a new merge-commit hash would result in a bunch of jobs being run for various open pull requests? (Sorry if that's an obvious question to you; it wasn't apparent to me so I thought I'd ask.)

Also I realize this has been open for awhile and I'm trying to remember when GitHub released the feature, but I'm wondering if rather than putting this change into the plugin, if instead folks should be directed to use the GitHub branch protection setting, which would stop someone from merging something if the actual merge commit has not been tested.

**Comment by chornlgscout** [comment]
It's a good question, and yes, the intent to provide an option to automatically rebuild any open PRs when the merge commit changes. Forcing manual rebuilds would also be an option, but not a preferable one for my particular use case.

**Comment by benpatterson** [comment]
@chornlgscout ok i hear you.

I will give this a closer look in the coming days.

**Comment by bjoernhaeuser** [comment]
I will close this for now - it is staled (sorry for that!) and has conflicts.

Is the underlying problem still present or is the protected branches setting the right thing to use?

If I misunderstood anything please leave a comment and we can try to move this forward.

**Pull request closed without merging**
