### PR TITLE
Add to whitelist comment triggers builds

### PR DESCRIPTION
**Pull request by kshtsk**
If admin tries to add someone to whitelist there is build triggered, but should not.

### CODE REVIEW

**Comment by benpatterson** [comment]
@kshtsk thank you for the pull request!

However, I wonder why you feel a build should not be triggered? If a build is not automatically triggered, then the submitter (or the admin) would need to add another comment to the request to start a build. I like that adding to whitelist automatically starts a build...that is the next logical thing to happen anyway, in my opinion.

**Comment by kshtsk** [comment]
The build should not be triggered because:
1) If you want to add a user or several users to whitelist and you're not going to trigger build right now, it will trigger you one ore several builds depending on configuration, especially in the situations when you select option to not trigger builds automatically 
2) It is confusing to expect build triggering from command of just updating a whitelist, if someone wants everything in one comment, then probably it is better to support of multiple commands per one comment, or create another like: add user to whitelist and test this please
3) It is not documented in the plugin and this behavior is unexpected, it was a big surprise when I first time used it
4) the next logical thing is not that build happens anyway, but builds happens whenever added person wants it, remember, you selected not to run build automatically

**Comment by kshtsk** [comment]
@benpatterson 
Oh, probably I misunderstood the feature of "add to whitelist" which should be, "add author to whitelist". It does not accept any user a parameter.
Okay, it is better to update the docs to exclude all confusing moments

**Comment by kshtsk** [comment]
@benpatterson 
Something wrong with the logic of this command anyway, for example, there is another correlated issue, if admin issued this command and user is already in a whitelist, the trigger will rise as well.
Admin still does not want to trigger the build, she only need to whitelist the user.

**Comment by benpatterson** [comment]
@kshtsk I don't want to add that kind of functionality right now, but I agree with your point that the documentation is unclear and this could lead to confusion.

I'm going to label this as something that needs documentation.

**Comment by samrocketman** [comment]
I'm not sure the `documentation` label is appropriate here.  I would think that `documentation` labels are for proposed changes which only change documentation.

The proper action here is to describe the desired behavior in an issue so that we can settle on a good design going forward and then propose a new PR based on that issue.

Please open an issue rather than a PR so we can discuss in it.

**Pull request closed without merging**
