### PR TITLE
update to support breaking change in github-api

### PR DESCRIPTION
**Pull request by JulienLajugie**
The method gitHttpTransportUrl has been removed from github-api (see commit https://github.com/github-api/github-api/commit/944d92bbb408dc7be91fcbe539a21762c6e0491a?diff=split). And because of that the ghprb plugin is broken. This change correct the issue.

### CODE REVIEW

**Comment by kmaehashi** [comment]
👍 
`gitHttpTransportUrl ` renamed to `getHttpTransportUrl` in github-api v1.91.
https://github.com/github-api/github-api/commit/5113aacb89de358ade715a09570396c1d9a7b11e

**Comment by kmaehashi** [comment]
Stacktrace:
```
A thread (Thread-71/1869) died unexpectedly due to an uncaught exception, this may leave your Jenkins in a bad way and is usually indicative of a bug in the code.
java.lang.NoSuchMethodError: org.kohsuke.github.GHRepository.gitHttpTransportUrl()Ljava/lang/String;
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.getAuthorRepoGitUrl(GhprbPullRequest.java:722)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.build(GhprbBuilds.java:75)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.build(GhprbPullRequest.java:555)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.tryBuild(GhprbPullRequest.java:548)
	at org.jenkinsci.plugins.ghprb.GhprbPullRequest.check(GhprbPullRequest.java:310)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.onIssueCommentHook(GhprbRepository.java:354)
	at org.jenkinsci.plugins.ghprb.GhprbTrigger.handleComment(GhprbTrigger.java:738)
	at org.jenkinsci.plugins.ghprb.GhprbRootAction$1.run(GhprbRootAction.java:238)
```

Workaround until this PR got merged: remove `JENKINS_HOME/plugins/github-api/` and `JENKINS_HOME/plugins/github-api.jpi`, put `github-api.hpi` ([v1.106](https://updates.jenkins.io/download/plugins/github-api/)) under `JENKINS_HOME/plugins` to downgrade github-api plugin, then restart Jenkins.

**Comment by JulienLajugie** [comment]
@kmaehashi you can also use the ghprb hpi that was build from this PR. It's available here: https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fghprb-plugin/detail/PR-772/8/artifacts/

**Comment by samrocketman** [comment]
I can take a look at this since it appears to be a breaking change.  I don't use GHPRB plugin (and haven't contributed in a couple of years) but I can fire up a Jenkins instance and test it out.

**Comment by JulienLajugie** [comment]
Just saw that this was merged and that a new version of the plugin was available. Thank you @samrocketman !

**Pull request merged**
