### PR TITLE
Add a pullRequests map to the job DSL

### PR DESCRIPTION
**Pull request by DavidTanner**
Fix issue brought up by @fstehle

### CODE REVIEW

**Comment by DavidTanner** [comment]
@daspilker @Eriten Would you please review this and help me get this right?

**Comment by daspilker** [comment]
For what are you using the map? It's never populated. If you just want to pass an empty map to the constructor of `GhprbTrigger`, you don't need to add the map to `GhprbTriggerContext`.

**Comment by mmitche** [comment]
@DavidTanner Yeah, that's not the right fix.  I am thinking the problem here is that when null is passed as the last parameter, the configuration won't be saved, due to this (and even an empty map won't do anything either)

```
if (super.job == null || pullRequests == null) {
            return;
        }
        boolean save = false;
        for (GhprbPullRequest pr : pullRequests.values()) {
            if (save || pr.isChanged()) {
                save = true;
                pr.save();
            }
        }
        if (!save) {
            return;
        }
        try {
            logger.log(Level.FINEST, "Saving config update for job");
            super.job.save();
        } catch (IOException e) {
            logger.log(Level.SEVERE, "Unable to save config updates", e);
        }
```

**Comment by mmitche** [comment]
What I'm unclear on is why this causes a rebuild of the full set of PRs.

**Comment by mmitche** [comment]
@DavidTanner As far as I understand, here is what is going on with job-dsl.  The plugin is taking what is written in the job dsl language and translates it to objects in your plugin.  That data is then serialized out to disk.  I think at that point, the trigger is started.

There is more info on how it's implemented here: https://github.com/jenkinsci/job-dsl-plugin/wiki/Extending-the-DSL

**Comment by DavidTanner** [comment]
The map is used to keep track of thre PRs that are open.  Without it the trigger goes through all of the comments each time it triggers and retrigger with each change.  Before it was a static asset, which it sounds like it still needs to be.

**Comment by daspilker** [comment]
Job DSL uses [AbstractItem#updateByXml](http://javadoc.jenkins-ci.org/hudson/model/AbstractItem.html#updateByXml(javax.xml.transform.Source)), so this may also affect any other plugin using this API, including the [Update Job CLI command](http://javadoc.jenkins-ci.org/hudson/cli/UpdateJobCommand.html) and the REST API.

I'm not sure if it's a good idea to store this kind of state in the job config. Maybe you should ask on the dev-list.

**Pull request closed without merging**
