### PR TITLE
Add Jenkinsfile

### PR DESCRIPTION
**Pull request by bjoernhaeuser**
@samrocketman 
Do you if we have to do something else for getting builds running?

### CODE REVIEW

**Comment by samrocketman** [comment]
@bjoernhaeuser feel free to merge.

**Comment by benpatterson** [comment]
Heads up... When ready, you can get this running in jenkinsci builds with a
request to the infra team.

**Comment by samrocketman** [comment]
It should automatically be picked up by Jenkins infrastructure by simply having a `Jenkinsfile`.  Refer to https://wiki.jenkins.io/display/JENKINS/Hosting+Plugins#HostingPlugins-ci.jenkins.io

> Once you've done this, your job will appear on ci.jenkins.io under the Plugins folder, and all subsequent branches and Pull Requests will be built.

**Comment by bjoernhaeuser** [comment]
Yep, everything is running now: https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fghprb-plugin/activity

**Comment by benpatterson** [comment]
Ah, awesome!

**Pull request merged**
