### PR TITLE
[JENKINS-55793] Configuration as Code support for GitHub Pull Request…

### PR DESCRIPTION
**Pull request by Holmistr**
… Builder plugin

See: https://issues.jenkins-ci.org/browse/JENKINS-55793

### CODE REVIEW

**Comment by maxstack** [comment]
Could you give a full example of the configuration required, along with required hierarchies? Eg:
```
unclassified:
  ghprbTrigger:
    extensions:
    - ghprbSimpleStatus:
        addTestResults: false
        showMatrixStatus: false
```

Thanks

**Comment by AndreaGiardini** [comment]
Hello @bjoernhaeuser Can we have an update on the status of this PR? Thanks! :)

**Comment by Holmistr** [comment]
Hi guys, I'm sorry, I'm a bit overloaded and completely forgot about this one. I will try to update it Monday the latest.

**Comment by wosc** [comment]
I'm very happy this is happening! If I'm not mistaken, the `GhprbGitHubAuth` will also have to be tweaked in order to be available for casc, so one can e.g. configure the public jenkins URL.

**Comment by EdSalisbury** [comment]
I'm really wanting to use JCASC for GHPRB!  Please approve/merge!

**Comment by bjoernhaeuser** [comment]
Could anyone tell me / show me why this is needed and why this is required for jenkins as code?

**Comment by madAndroid** [comment]
@bjoernhaeuser - it's not currently possible to set all the options in the Jenkins global config via JCasC - in particular, we're looking to set/unset the `Auto-manage webhooks` option - since having this enabled has caused us to drain the Github API limits with a list of jobs created using the Jenkins JobDSL

**Comment by bjoernhaeuser** [comment]
Okay, that I understand. But could someone point me to the documentation what needed for JASC in general? How does it interact with plugins? What do plugins need to provide? 

Thank you!

**Comment by elasticdog** [comment]
@bjoernhaeuser Looks like there are some upstream [docs](https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/docs) that cover the details for plugin developers:
- https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/PLUGINS.md
- https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/REQUIREMENTS.md

**Comment by brettcat** [comment]
Will this enable me to set the "Shared secret" and the "Credentials"?

Screen Shot 2019-07-25 at 6 04 23 PM

**Comment by tstrul1** [comment]
Hi, any updates on this? We are migrating our Jenkins solution to JCASC and we would really like to keep using GHPRB

**Comment by Holmistr** [comment]
Hey guys, I know it's been a long time, but I'm back. I got a bit lost. What prevents from merging this?
Don't know who to ask, @maxstack @bjoernhaeuser ?

**Comment by pallam-bigfoot** [comment]
Can we use GitHub link as configuration source. I am getting the error as shown in the attached screenshot. I have established connection between this jenkins instance and our GitHub using a Personal Access Token. Can you please let me know if i am doing something wrong here.
Screen Shot 2019-10-03 at 10 34 20 AM

**Comment by matthack** [comment]
@Holmistr looking forward to using this. Is this something that can be merged?

**Comment by hectoralicea** [comment]
Would like to see this change be merged in.

**Comment by ish-xyz** [comment]
Can you please merge?

**Comment by Holmistr** [comment]
I would love to merge it, but I can't. @maxstack what is left so we could merge this?

**Comment by Holmistr** [comment]
I'm happy to do the adjustments that are required to get this merged. Just give me a list and I'll do it :)

**Comment by diegolovison** [comment]
I would like set the Credentials.
I don't see how we could do that with this PR

Screen Shot 2020-12-10 at 16 20 11

**Review by janinko — APPROVED** [review]

**Comment by janinko** [comment]
I don't want to step on anyones feet, but there doesn't seem to be much activity from the maintainers lately and it seems we need this merged, so I'm merging it.

**Comment by Holmistr** [comment]
:tada:

**Comment by odockal** [comment]
@janinko Much appreciated! Diky

**Comment by calvinpark** [comment]
> I would like set the Credentials.
> I don't see how we could do that with this PR
> 
> Screen Shot 2020-12-10 at 16 20 11

@Holmistr @janinko Can you please clarify whether the credentials can be set with JCasC?

**Comment by Holmistr** [comment]
@calvinpark I guess it's not possible with this PR but it can certainly be added :)

BTW @janinko how will we handle the release if the maintainers are not active? Is it possible to do it? Perhaps I can take over?

**Comment by janinko** [comment]
@Holmistr https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/

**Comment by batmat** [comment]
Thanks for the contribution @Holmistr!

For anybody looking here and using this plugin (I'm not, I came for the dev ML thread), I quite strongly recommend to look into adding also a test for this code.

See https://github.com/jenkinsci/email-ext-plugin/pull/211/files for an example (in this PR, only a test was added to harness the behavior and "keep it working" like we should do here to avoid future potential regressions). 
This is quite easy to do as you will see.

Cheers!

**Comment by sp-ricard-valverde** [comment]
> > I would like set the Credentials.
> > I don't see how we could do that with this PR
> > Screen Shot 2020-12-10 at 16 20 11
> 
> @Holmistr @janinko Can you please clarify whether the credentials can be set with JCasC?

I just tested to dump the _jcasc_ config after setting the Credentials and apparently they can be configured too:

Captura de pantalla 2021-01-13 a las 15 08 33

````yaml
unclassified:
  ghprbTrigger:
    autoCloseFailedPullRequests: false
    cron: "H/5 * * * *"
    extensions:
    - ghprbSimpleStatus:
        addTestResults: false
        showMatrixStatus: false
    githubAuth:
    - credentialsId: "7413acf9-29fe-41ce-ba6a-0fb5937f45be"
      description: "Some user"
      id: "5a8f4f1b-99dc-4c56-bbae-29b942ab96b2"
      secret: "{AQAAABAAAAAQqdOT7klptqQtHb7BsoS/p0go02Z1/PBNJfD9ikIPTvM=}"
      serverAPIUrl: "https://api.github.com"
    manageWebhooks: true
    okToTestPhrase: ".*ok\\W+to\\W+test.*"
    requestForTestingPhrase: "Can one of the admins verify this patch?"
    retestPhrase: ".*test\\W+this\\W+please.*"
    skipBuildPhrase: ".*\\[skip\\W+ci\\].*"
    useComments: false
    useDetailedComments: false
    whitelistPhrase: ".*add\\W+to\\W+whitelist.*"
````

Although I'm not 100% sure but the _secret_ might not work across Jenkins installations due to salted hashing, again, not sure on that.

**Comment by calvinpark** [comment]
@sp-ricard-valverde which secret type are you using? I'm using `string` to hold the personal access token, and that doesn't show up under `unclassified/ghprbTrigger/githubAuth`

**Comment by sp-ricard-valverde** [comment]
I believe `secret` is actually the field `Shared secret` which is the Webhook token, not related to the `Credentials` field.

**Comment by fabiankle** [comment]
@sp-ricard-valverde : How did you obtain this output/jcasc dump as above? Which version/branch of the plugin are you using here? 
(For me, jcasc does not put out anything for this plugin, nor accept it; I've been googling this forever now as I need to set the serverAPIUrl by CaC and your post is the first actual example for this)

**Comment by sp-ricard-valverde** [comment]
> @sp-ricard-valverde : How did you obtain this output/jcasc dump as above? Which version/branch of the plugin are you using here?
> (For me, jcasc does not put out anything for this plugin, nor accept it; I've been googling this forever now as I need to set the serverAPIUrl by CaC and your post is the first actual example for this)

The needed changes(which are in this very PR) are merged into `master` but not yet released. I had to manually build the plugin and install it to test the configuration.
This request tracks an eventual 1.42.2 plugin release with jcasc capabilities: https://github.com/jenkinsci/ghprb-plugin/issues/807

**Comment by fabiankle** [comment]
@sp-ricard-valverde : ah, good to know, thank you!!

**Comment by calvinpark** [comment]
@sp-ricard-valverde would you mind sharing the hpi? I'd love to try it myself. Thank you

**Comment by sp-ricard-valverde** [comment]
> @sp-ricard-valverde would you mind sharing the hpi? I'd love to try it myself. Thank you

Sorry I don't have it anymore. Also, as a side note, it's not something you'd want to install from an untrusted source.

**Comment by Holmistr** [comment]
@calvinpark Just checkout the master branch of this repository and run `mvn clean package`. You should find the HPI in the `target` directory. (writing it from the top of my head, hopefully I remember it correctly)

**Pull request merged**
