### PR TITLE
Format README and test code

### PR DESCRIPTION
**Pull request by bjoernhaeuser**
In #599 we added checkstyle config and formatted the code. 

This does the same for test code.

### CODE REVIEW

**Comment by bjoernhaeuser** [comment]
@samrocketman Do you think you have time for looking at this? Would love to get this into the next release.

**Comment by samrocketman** [comment]
I'll have time to review this, this evening (it's currently morning for me).

**Comment by bjoernhaeuser** [comment]
@samrocketman 

Happy new year to you! Would be great if we can merge this soonish :)

**Comment by samrocketman** [comment]
I'll review this today.

**Pull request merged**
