### PR TITLE
Fix credentialsId being null

### PR DESCRIPTION
**Pull request by DavidTanner**
The credentialsId may/may not be null, so just replace it with the default empty string.

### CODE REVIEW

**Comment by DavidTanner** [comment]
@arcivanov this affects resolving variables if credentialsId isn't set

**Comment by arcivanov** [comment]
Not enough, unfortunately. See https://github.com/jenkinsci/ghprb-plugin/blob/envVars/src/main/java/org/jenkinsci/plugins/ghprb/GhprbTrigger.java#L293 - `getGitHubApiAuth()` can return `null` as well

**Comment by DavidTanner** [comment]
I believe the code path guarantees that auth will never be null, it will either be what the user has set up some credentials, or it will use an anonymous connection.

**Comment by arcivanov** [comment]
I think you're right and there can never be a case of an NPE there but then the code at L239 is unnecessary.

**Comment by DavidTanner** [comment]
Done.

**Comment by arcivanov** [comment]
LGTM :+1:

**Comment by arcivanov** [comment]
Ready or you're still working on it?

**Pull request merged**
