### PR TITLE
GhprbPullRequestMerge must NOT persist and serialize logger #192

### LINKED ISSUE #192: GhprbPullRequestMerge must NOT persist and serialize logger
Otherwise `config.xml` contains lovely things like this after a build:

```
    <org.jenkinsci.plugins.ghprb.GhprbPullRequestMerge plugin="ghprb@1.28-SNAPSHOT">
      <logger>
        <out class="hudson.plugins.timestamper.TimestamperOutputStream" plugin="timestamper@1.7.2">
          <delegate class="java.io.FileOutputStream">
            <fd>
              <fd>739</fd>
              <parent class="java.io.FileOutputStream" reference="../.."/>
              <closed>false</closed>
            </fd>
            <append>false</append>
            <path>/mnt/data/config/jobs/HCS_-_Main_-_(PR)_-_(Autogen)/builds/1/log</path>
            <closeLock/>
            <closed>false</closed>
          </delegate>
          <timestampsWriter>
            <timestampsFile>/mnt/data/config/jobs/HCS_-_Main_-_(PR)_-_(Autogen)/builds/1/timestamper/timestamps</timestampsFile>
            <timestampsDigest class="com.google.common.base.Optional$Present">
              <reference class="java.security.MessageDigest$Delegate">
                <algorithm>SHA-1</algorithm>
                <state>1</state>
                <provider class="sun.security.provider.Sun" serialization="custom">
                  <unserializable-parents/>
                  <hashtable>
                    <default>
                      <loadFactor>0.75</loadFactor>
                      <threshold>125</threshold>
                    </default>
                    <int>167</int>
                    <int>100</int>
```
and etc _ad nauseam_, including on occasion entities that are illegal in XML (`&#x1B;`) and tons (tens of kilobytes) of binary encoded data.

### PR DESCRIPTION
**Pull request by arcivanov**
fixes #192, connected to #192

### CODE REVIEW

**Comment by arcivanov** [comment]
@DavidTanner review please

**Comment by arcivanov** [comment]
Let me know if I'm out of line but I'll merge this and cut a release - this breaks Jenkins config.xml validity and bogs it down dramatically.

**Comment by DavidTanner** [comment]
Looks good to me, I didn't realize it was saving it.

**Comment by arcivanov** [comment]
I found out the hard way :smile:

**Comment by arcivanov** [comment]
@DavidTanner do I need to do anything special to upload the release 1.28.5 to mirrors? I still don't see it on update sites.

**Comment by DavidTanner** [comment]
They only update things six times a day

**Comment by DavidTanner** [comment]
Did you get permissions to upload to the jenkins maven servers?   At the end of the release process you should see the files being uploaded.

**Comment by arcivanov** [comment]
I only did release:prepare but no release:perform. No I didn't and no one mentioned that to me when I asked. :sigh:

**Pull request merged**
