### PR TITLE
Revert pipeline changes for the UpstreamStatusListener.

### PR DESCRIPTION
**Pull request by benpatterson**
Putting this up for now; will ask for feedback on approach.

### CODE REVIEW

**Comment by benpatterson** [comment]
Addresses #506 

@mshuler based on my local testing, this should fix your issue. It's basically falling back to what it had been using for this part of the plugin. Is this something you can test if you build locally? Thought I'd ask before packaging + releasing it.

**Comment by benpatterson** [comment]
In part because I likely won't log on again for several days, I'm going to merge now and release. Again local testing tells me the issue is fixed but I'd love feedback one way or another.

**Comment by benpatterson** [comment]
released with 1.36.2

**Comment by mshuler** [comment]
Thanks - I don't have time at the moment to do a local build, but I'll test out this release and let you know. I appreciate your time!

**Comment by mshuler** [comment]
Upgraded to 1.36.2, triggered a PR build, and my 2 downstream jobs just updated the PR with "Build started", so this looks good to me! Thanks again.

**Pull request merged**
