### PR TITLE
exposes PR description as environment variable

### PR DESCRIPTION
**Pull request by joseph-chu**
This PR exposes the PR description (the text you are reading right now) as the environment variable `ghprbPullLongDescription`.

### CODE REVIEW

**Comment by DavidTanner** [comment]
I think some work needs to be applied to the environment variables, and so would like to hold off on merging this if that is alright with you.

**Comment by joseph-chu** [comment]
Do you mean that there's work to be done concerning environment variables on the main branch, or that this PR in particular needs work?

Either way it's fine, I'm using my fork.  Would like to revisit soon.

**Comment by DavidTanner** [comment]
There are several open issues about environment variables that are created by the plugin in general.  I am just thinking the way they are added needs some attention.  Nothing specific to your request.  Maybe a way to add variables without a code change.

**Comment by joseph-chu** [comment]
This PR just pipes `GHPullRequest.getBody()` through four classes so it can be exposed in `GhprbTrigger`, which does seem kind of unwieldy.  Avoiding code changes seems difficult since they don't all come from a single source but I'll hold off until a decision is made about that.

**Comment by DavidTanner** [comment]
Most of the environment variables are just parts of the pull request.  If there were something that you could pick and choose what fields come through, and even pick the names then adding the body would just be a matter of adding/changing a setting in the job configure page.

**Pull request closed without merging**
