### PR TITLE
Bump github-api to 1.90

### PR DESCRIPTION
**Pull request by SqREL**
Life critical fix because of kohsuke/github-api#387

### CODE REVIEW

**Comment by rholder** [comment]
It turns out just bumping up the version wasn't enough. I've opened up #589 to help move this forward. If you're currently watching this or another related issue, feel free to add a code review over there and help get it tested.

**Comment by shevek** [comment]
+1

**Comment by Harriebo** [comment]
+1

**Comment by Dyakovvn** [comment]
+1

**Comment by santiagocanti** [comment]
+1

**Comment by coladarci** [comment]
+1

**Comment by lolpack** [comment]
+1

**Comment by BreaGaudioso** [comment]
+1

**Comment by samrocketman** [comment]
This change is superseded by the merged #589.

**Comment by bjoernhaeuser** [comment]
@shevek @Harriebo @Dyakovvn @santiagocanti @lolpack @BreaGaudioso 

These "+1" comments are not really helping. ;) You can add your reaction in the first comment and subscribe on the right side.

**Comment by samrocketman** [comment]
Alternatively, if you +1 is intended as a review; feel free to make use of the review features GitHub provides.

**Comment by shevek** [comment]
We're lazy. We just want this magical "open source" thing we've all heard of to solve all the world's problems. When I can't open the door of my fridge because it's updating the firmware, I just go to github and put a +1 on Samsung/FridgeDoor.git and hope they release a firmware update before my milk goes off.

Also, we have the fix now, thank you.

**Pull request closed without merging**
