### PR TITLE
Parent pom update

### PR DESCRIPTION
**Pull request by benpatterson**

### CODE REVIEW

**Comment by benpatterson** [comment]
@mmitche This should resolve some injector tests errors. Plus it's good hygiene.

**Comment by mmitche** [comment]
LGTM, this doesn't change the core supported version, right?

**Comment by benpatterson** [comment]
@mmitche as far as I understand the plugin dependencies, no. We're not changing signatures of anything in the plugin itself, and are in fact still using deprecated methods. 2.7 came out about 5 months ago so we're still leaving some legroom in case I'm missing something.

**Comment by benpatterson** [comment]
Oh I should point out that I upgraded the git version to something that is still relatively old, but there were some guava dependencies that we needed. The github-api plugin is updated for similar reasons (IIRC it was a nested thoughtworks dependency.)

**Pull request merged**
