### PR TITLE
Use configured context for all status update callbacks

### LINKED ISSUE #567: Configured context is not used for all status updates
Only the build triggered status update uses the configured context, the build started and build completed do not and go back to "default".

This prevents the check to ever be completed:
image

Looking at the code in GhprbSimpleStatus.java, the build triggered callback sets the status differently than the other two.

### PR DESCRIPTION
**Pull request by texasaggie97**
* Fixes #567 
* When the context is configured to something other than an empty string, it is only used for the "build triggered callback" and not the "build started" or the "build finished" callbacks. This will leave unfinished checks in the PR status:
image

* After this change, the check is marked as finished even when using non blank context strings:
image
(Ignore the "default" line. I have been testing on a single PR so that is left over from when I was using a blank string)

* GhprbSimpleStatus.java uses different mechanisms for setting the context depending on which callback is running. I did not try to make them all the same.
  * "build triggered" callback gets the context before setting the status
  * "build started" and "build finished" callbacks just use the class variable for the context.

* Fix is to set the class variable to what is retrieved from configuration during "build triggered" if it is empty
  * Required not setting commitStatusContext as final since this changes the value later.

### CODE REVIEW

**Comment by samrocketman** [comment]
@texasaggie97 I like this change; any chance you could add some tests?

**Comment by texasaggie97** [comment]
I have not been able to figure out how to configure the test framework to have a properly set up global instance of `GhprbSimpleStatus`.

I have also not been able to figure out how to mock `GhprbSimpleStatus.DescriptorImpl` because it is final.

If you have any suggestion on how I can approach this, I am happy to add tests.

**Comment by samrocketman** [comment]
There are some tests already written for this class.  https://github.com/jenkinsci/ghprb-plugin/blob/master/src/test/java/org/jenkinsci/plugins/ghprb/extensions/status/GhprbSimpleStatusTest.java

In general, you want to unit test just the class itself (as a unit).  That means external classes should be mocked.  You can also refer to other tests in this repo which contain mocking examples.

If you feel you need help, then feel free to add me as a contributor to your project and I can help with tests.

**Comment by texasaggie97** [comment]
I have been trying to figure out what to mock to make this work.

The change requires access to the default values, which means `Ghprb.getDefaultValue()` needs to access both the local instance, and the global instance. The default value comes from the global instance.

I merged in and pushed my latest attempt.

Other things I have tried included calling `GhprbTestUtil.setupGhprbTriggerDescriptor()` at different times.

I also tried setting additional values when calling `GhprbTestUtil.getTrigger()`.

Since none of these have worked, I added you as a collaborator.

**Comment by texasaggie97** [comment]
I pushed a different attempt at testing. In this one I added a global extension, as seen in a different test. It still didn't work.

**Comment by samrocketman** [comment]
I accepted your invitation and will check out your changes tomorrow.  Additionally, I'll help out with tests as promised.

**Comment by samrocketman** [comment]
Hi @texasaggie97, I haven't had a chance to getting around to figuring out how to properly test this.  Please update your change with the latest master.  If the build passes and I'm able to successfully manually test it then I'll say good enough for now.  This change actually fixes a bug I experience.

**Comment by texasaggie97** [comment]
Okay, I have updated from the master branch and fixed merge conflicts.

**Pull request merged**
