### PR TITLE
NPEs in 1.28

### LINKED ISSUE #184: 1.28 fails with NPEs
```
Sep 22, 2015 10:15:29 PM SEVERE org.jenkinsci.plugins.ghprb.Ghprb getEnvVars
Couldn't get Env Variables: 
java.lang.IllegalArgumentException: Null value not allowed as an environment variable: ghprbAuthorRepoGitUrl
	at hudson.EnvVars.put(EnvVars.java:356)
	at hudson.model.StringParameterValue.buildEnvironment(StringParameterValue.java:56)
	at hudson.model.ParametersAction.buildEnvVars(ParametersAction.java:88)
	at hudson.model.AbstractBuild.getEnvironment(AbstractBuild.java:944)
	at org.jenkinsci.plugins.ghprb.Ghprb.getEnvVars(Ghprb.java:276)
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.createCommitStatus(GhprbSimpleStatus.java:183)
	at org.jenkinsci.plugins.ghprb.extensions.status.GhprbSimpleStatus.onBuildComplete(GhprbSimpleStatus.java:178)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onCompleted(GhprbBuilds.java:172)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:32)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:17)
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:199)
	at hudson.model.Run.execute(Run.java:1783)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
```

### PR DESCRIPTION
**Pull request by arcivanov**
fixes #184, connected to #184

### CODE REVIEW

**Comment by jlebon** [comment]
The real question is why are those variables null in the first place. This might be masking a larger issue at play.

**Comment by arcivanov** [comment]
When the build is triggered via comment rather than a fresh commit into a PR the "author" misses whole bunch of fields, which would be expected. The `statusUrl` can be null coming from overloaded constructors.

**Comment by arcivanov** [comment]
I just had a full build run successfully with this fix 
@DavidTanner, review please?

**Comment by arcivanov** [comment]
```
2015-09-22 23:04:52.911: GitHub pull request #40 of commit 08fc34dfb1ee596d3e0afae90d121fccb4412e6a, no merge conflicts.
2015-09-22 23:04:53.168: Setting status of 08fc34dfb1ee596d3e0afae90d121fccb4412e6a to PENDING with url  and message: 'Build started sha1 is merged.'
2015-09-22 23:04:53.208: [EnvInject] - Loading node environment variables.
2015-09-22 23:04:53.631: Setting status of 08fc34dfb1ee596d3e0afae90d121fccb4412e6a to PENDING with url  and message: 'Build has started, please wait for results...'
```

```
2015-09-22 23:10:08.105: Setting status of 08fc34dfb1ee596d3e0afae90d121fccb4412e6a to SUCCESS with url  and message: 'Build finished. 69 tests run, 0 skipped, 0 failed.'
```

**Pull request merged**
