### PR TITLE
Give more examples for setting up webhook

### PR DESCRIPTION
**Pull request by ryanwalls**
I ran into problems because I thought the path to the webhook was /jenkins/ghprbhook/ when in fact the path is just /ghprbhook/. The example in the documentation assumed users were running jenkins at /jenkins on their server. This PR clarifies the documentation and provides examples of two common types of configurations.

### CODE REVIEW

**Comment by jbeorse** [comment]
I agree. I was similarly confused and experimented with both. I think this change clarifies.

**Comment by bjoernhaeuser** [comment]
@ryanwalls Thank you very much for the fix!

Though I still think that the new text is not very clear about why or why not use the `/jenkins` prefix. I think the documentation should mention that the hook is basically the same as the jenkins url itself. And that the user only has to provide `/jenkins` if thats also the base url for jenkins.

What do you think?

**Comment by ryanwalls** [comment]
@bjoernhaeuser That's why I put `<code>< your jenkins server url >/ghprbhook/</code>`.  I wanted to be clear that it is just your jenkins server url plus the ending part.  I can state that in a sentence if you think it would be useful/more explicit.

Or I could just remove the examples.  The part with `e.g.`  Examples may actually cause more confusion than good.

**Comment by bjoernhaeuser** [comment]
@ryanwalls I think adding a explaining sentence would be great! Thanks!

**Comment by ryanwalls** [comment]
@bjoernhaeuser Added some clarification.

**Comment by bjoernhaeuser** [comment]
Thanks!

**Pull request merged**
