### PR TITLE
Fix issue janinko/ghprb#232 due to changes in underlying api

### PR DESCRIPTION
**Pull request by ddumontatibm**

### CODE REVIEW

**Comment by ddumontatibm** [comment]
@DavidTanner I really need this fix.  I addressed your questions in janinko/ghprb#261

**Comment by ddumontatibm** [comment]
@DavidTanner ty.  When do you think there could be a release of the plugin so I can pick up the fix?

**Comment by DavidTanner** [comment]
I released a new version shortly after merging your pull request

**Comment by ddumontatibm** [comment]
@DavidTanner Sorry for being a pain, but 
https://github.com/janinko/ghprb/commits/master and 
https://github.com/jenkinsci/ghprb-plugin/commits/master

Do not show any of the maven release plugin commits for the new version.

**Comment by DavidTanner** [comment]
Well, I started the process... but I got distracted and there it was this morning in my console waiting for a version.  Sorry, I am releasing now.

**Comment by ddumontatibm** [comment]
Thanks a bunch!

**Pull request merged**
