### PR TITLE
Fix NPE

### PR DESCRIPTION
**Pull request by mmitche**
Ghprb.extractTrigger could return null

### CODE REVIEW

**Comment by DavidTanner** [comment]
Have you actually run into this scenario? The projects list is only populated by projects that have the trigger.

**Comment by mmitche** [comment]
I have, which leads me to believe there is some other bug somewhere.  I'm pretty sure that a restart will fix the problem.  I believe it's happening for one set of projects right now on dotnet-ci.  Any ideas on how to debug it without taking down the server?

**Comment by DavidTanner** [comment]
When the trigger is stopped then it should be removed from the projects array. You might be able to save the config again, and that might do it.

**Comment by mmitche** [comment]
@DavidTanner Not sure what the project was, it may be possible that it was disabled at the time.

Either way this is all automatic on our side, there is no manual interaction with job configurations, so we should get to the bottom of the for now.  At the very least, can I alter this so that if null is returned, a warning is printed?  We should catch null to avoid odd bugs, since it ends up blocking any other trigger from starting, but we should also be able to diagnose it.

**Comment by mmitche** [comment]
@DavidTanner changed to introduce more info.

**Pull request merged**
