### PR TITLE
Get comment file from workspace, fixes #343

### LINKED ISSUE #343: FileNotFoundException when using comment file path
I'm trying to use comment file path to add comment to PRs with some analysis results read from a text file that has previously been created during build phase. According to build log, reading comment file seems to be the last build step that was executed, which means the file should already exist at that point, but I still get `FileNotFoundException`. The path I use is `${WORKSPACE}/path/to/comment/file` and I double check to make sure it exists.

The job was executed on a remote slave machine, which is connected by Jenkins master via SSH. I suspect the plugin was trying to read a file on Jenkins master and thus couldn't find the file, whose path is meant for the slave machine, but I could be wrong.

Some context:
- Jenkins version: 1.651.1
- Gihub plugin version: 1.18.1
- Github API plugin version: 1.72.1
- Github authentication plugin version: 0.22.3
- GHPRB plugin version: 1.31.2

Full stack trace:

```
Couldn't read comment file
java.io.FileNotFoundException: File '/var/slave/workspace/job/lint-results.txt' does not exist
    at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:299)
    at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1711)
    at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1748)
    at org.jenkinsci.plugins.ghprb.extensions.comments.GhprbCommentFile.postBuildComment(GhprbCommentFile.java:45)
    at org.jenkinsci.plugins.ghprb.GhprbBuilds.commentOnBuildResult(GhprbBuilds.java:227)
    at org.jenkinsci.plugins.ghprb.GhprbBuilds.onCompleted(GhprbBuilds.java:202)
    at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:32)
    at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:17)
    at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:201)
    at hudson.model.Run.execute(Run.java:1783)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:410)

!!! Couldn't read commit file !!!
```

### PR DESCRIPTION
**Pull request by jrudolph**
Using the workspace will find the comment file even when the build was executed on a slave node.

### CODE REVIEW

**Comment by reverson** [comment]
What's the status of this Pull Request? I'm running into this issue, and my current setup uses 0 executors on the master, so I can't pin this job to the master.

**Comment by reverson** [comment]
Can one of the admins verify this patch?

**Comment by reverson** [comment]
@benpatterson (sorry to @ you directly, I see you're generally the most active). What needs to be done to have this looked at?

Sorry to be pushy, I just fought with this behavior for a good few hours before I realized what was going on.

**Comment by roguishmountain** [comment]
Hi @benpatterson, do you know when you'll have time to verify and merge this patch? I tested this patch locally and it seems to work. The merge conflicts are minor and the style guide issues are also minor. I'm not sure if you are the correct person to tag, but it looks like you have done all the releases recently. Thanks!

**Comment by benpatterson** [comment]
Hi @roguishmountain -- Sorry for the quiet on my end. I am no longer the maintainer; however the new maintainers have been somewhat engaged. I CC @bjoernhaeuser and @samrocketman here in case they can give you a better idea/feedback.

**Comment by samrocketman** [comment]
@roverson @jrudolf can this be rebased off of the latest master?

**Comment by jrudolph** [comment]
I merged it with the Github interface.

**Comment by samrocketman** [comment]
Question: I'm not familiar with this feature of GHPRB.  Can you describe more about it?  

In general, I personally avoid workspaces in lieu of API calls directly to GitHub when possible.

Note: my question doesn't block review or merging.  Just a curiosity.  I'll review this after work hours.

**Comment by samrocketman** [comment]
Also, looks like the Jenkins build returned checkstyle errors.  @bjoernhaeuser added checkstyle to improve maintenance going forward.  Please update so the checkstyle passes.

**Comment by roguishmountain** [comment]
@samrocketman This feature allows you to create custom messages to post on the PR that was built. Normally after the commit is built there is a Jenkins wide message that gets posted to the PR such as "commit failed to build" or "commit succeeded". This feature allows you to create a file in the workspace and the content of that file will also get posted to the PR. previously, the plugin would look for this file on the jenkins server. this PR changes this to search in the project workspace for the file. @jrudolph has an example of this here: https://github.com/akka/akka-http/pull/865#issuecomment-295293356

**Comment by samrocketman** [comment]
@roguishmountain thanks for taking the time to explain.  I fully understand now.  It makes sense to support loading from workspaces on agents and not force building on master for this feature (building on master being a known bad practice).

As soon as this is updated fixing the build issues I'll take the time to review and test upgrade ability.

**Comment by jrudolph** [comment]
Fixed the checkstyle issues.

**Comment by jrudolph** [comment]
Thanks for merging, @samrocketman!

**Comment by tomqwu** [comment]
Is this part of 1.40 release? if not how can I get it?

**Comment by ntindall** [comment]
has this been published with `1.42.0` ? I am still seeing this issue..

**Comment by samrocketman** [comment]
Looking at the merge commit https://github.com/jenkinsci/ghprb-plugin/commit/3df5a933e9ac574a567c4bf911a9646eb257177d it is indeed part of the 1.42.0 release.

**Pull request merged**
