### PR TITLE
Add support to restrict pull requests to defined paths

### PR DESCRIPTION
**Pull request by tlusk**
This adds the ability to define a list of regions to include
or exclude from the pull request builder trigger.

This should solve issue #221

### CODE REVIEW

**Comment by DavidTanner** [comment]
If you don't mind, would you please pull the configuration out of the trigger and make it an extension instead?

**Comment by tlusk** [comment]
Sure I'll look into doing that

**Comment by emoshaya-cognito** [comment]
this is exactly what I need :)

**Comment by MSch** [comment]
This is super amazing. We've recently rolled this out for our cross-platform project that supports Android, iOS and other platforms and it has resulted in a huge improvement to our build queue. PRs that don't touch Android code now no longer trigger Android builds and vice versa for iOS.

Is there something we can help with to get this merged & released?

**Comment by jchauncey** [comment]
Yeah would like to know if there is something I can do to help get this merged. Would love to get this on our jenkins hosts.

**Comment by kyhavlov** [comment]
how does this work with required checks on github? if your PR doesn't trigger because it only changed certain file types, does it just never pass the checks?

**Comment by manuinsfx** [comment]
This would help us a lot in our setup. I would love to see this merged.

**Comment by jrazgunas** [comment]
It looks like this checks all the files changed in a PR against a regular expression(s) and determines if the job should build based on a match of the regex pass or fail. It would be pretty cool if this could get merged, is anyone familiar enough with this plugin to support this functionality as an extension?

**Comment by jchauncey** [comment]
Where are we at with this PR? Does it need to be updated and resubmitted so we can get it merged?

**Comment by jrazgunas** [comment]
latest needs to be merged in, and the code changes need to be implemented as an extension.

**Comment by benpatterson** [comment]
Hi I'm lending a hand on this repo. As @jrazgunas pointed out, the next things for this are re-implementing the change as an extension, and resolving the merge conflicts.

**Comment by dulvac** [comment]
+1 for this. Let me know if I can help in any way.

**Comment by benpatterson** [comment]
@dulvac It will be a little while (couple weeks?) before I've ramped up & cleared up enough things to work on this one myself, so if you are particularly eager, you should just look at the other implementations in the [extensions directory](https://github.com/jenkinsci/ghprb-plugin/tree/master/src/main/java/org/jenkinsci/plugins/ghprb/extensions) if we don't hear from @tlusk

**Comment by tlusk** [comment]
We are no longer using Jenkins for our CI so I won't be re-implementing this as an extension, but I rebased it against the latest and fixed the conflicts.

**Comment by ctlam** [comment]
+1 @tlusk This works perfectly in our environment.  Love to see this merged into master.

**Comment by botchniaque** [comment]
Can you show example usage of `includeRegions` in job dsl? 
I have:
1. built hpi locally
2. uploaded it using _PluginManager Upload plugin_ site. 
3. restarted jenkins
4. verified that I have correct plugin version installed (`1.33.2-SNAPSHOT (private-59ce2292-sbochniak)`)
5. Added `includedRegions` into my job dsl
```
  triggers {
            githubPullRequest {
                // ...
                includedRegions('my-project/.*')
              //...
```
6. I get below error:
`ERROR: (script, line 39) No signature of method: javaposse.jobdsl.dsl.helpers.triggers.TriggerContext.includedRegions() is applicable for argument types: (java.lang.String) values: [my-project/.*]`



Did I do anything wrong?

**Comment by emoshaya-cognito** [comment]
can we get this merged please?

**Comment by mcummingscb** [comment]
Seriously, this is my co-worker, we are still using his fork on one Jenkins system.  This is super useful functionality.

**Comment by benpatterson** [comment]
Hi - This is still on my queue but I'm continuing to play catch up on open issues. If anyone wants to help push this along, the next thing I'd do on this is add tests in order to prevent regressions.

**Comment by soumyabk** [comment]
@botchniaque were you able to get your issue resolved?

**Comment by emoshaya-cognito** [comment]
Is this ever going to be merged or shall I just start using the forked version?

**Comment by benpatterson** [comment]
Sorry guys; the cycles I've had, I've spent on key bug fixes and Jenkins 2 stuff. Hopefully I'm over that hump now. This is still on the list. 

However, there are no explicit tests on this changeset, and that's making me hesitate in particular. I recognize the value in this feature but don't want to merge it without some tests that the regions would be respected (or not, depending on one's configuration). There are assertions on existing tests but I wanted something more directly testing the feature & settings. That would prevent regressions later on and reduce any manual testing needs.

**Comment by tlusk** [comment]
@benpatterson I added some unit tests to check if the trigger regions are matching correctly for you

**Comment by emoshaya-cognito** [comment]
Hi @benpatterson, could you please review the above added tests? If not, do you have an idea when this can be reviewed and merged? I really need this feature but would rather not use the forked version.

**Comment by benpatterson** [comment]
Hi folks. I will review in the coming week. Thanks for checking in...

**Comment by Spea** [comment]
Any news on this one? Can I somehow help to get this merged?

**Comment by bjoernhaeuser** [comment]
Awesome PR! Thanks very much. Do mind resolving the merge conflicts?

**Comment by bjoernhaeuser** [comment]
Just wanted to let you know that we are running this in production and it works great, thanks!

**Comment by benpatterson** [comment]
Alright. Let's do this. The various rebases and added tests are very much appreciated. To me the code looks fine overall. Now that we have the tests nothing is sticking out to me. I realize we didn't get this in as an extension but we can defer that.

**Comment by benpatterson** [comment]
Released in v 1.38.0. It'll take ~24 hours to appear on the Jenkins infrastructure for pulling onto your systems.

**Pull request merged**
